### ISSUE TITLE
[EPIC] Ability to simulate ransomware

### ISSUE THREAD

**Issue by jborozco** [OpenBAS-Platform/openbas#1386]
## Use case

1. Be able to simulate an end to end ransomeware scenario from OpenBAS
2. Be able to generate a valid ransomeware simulation from an OpenCTI report 

## To be done

- [ ] https://github.com/OpenBAS-Platform/openbas/issues/1415
- [ ] https://github.com/OpenBAS-Platform/openbas/issues/1414
- [ ] https://github.com/OpenBAS-Platform/openbas/issues/1413
- [ ] https://github.com/OpenBAS-Platform/openbas/issues/1416
